const KEY='bienestar-html-records';
let records=JSON.parse(localStorage.getItem(KEY)||'null')||[
 {id:1,name:'Mariana López',sex:'Mujer',age:31,department:'Ventas',position:'Ejecutiva comercial',housing:'Propia',economy:'Buena',debt:'21-40%',credits:['Tarjeta'],training:['Liderazgo'],status:'Completada',date:'2026-07-16'},
 {id:2,name:'Carlos Ramírez',sex:'Hombre',age:42,department:'Operaciones',position:'Supervisor',housing:'Infonavit',economy:'Regular',debt:'41-60%',credits:['Infonavit'],training:['Excel'],status:'Completada',date:'2026-07-15'},
 {id:3,name:'Sofía Hernández',sex:'Mujer',age:26,department:'Tecnología',position:'Analista',housing:'Rentada',economy:'Buena',debt:'0-20%',credits:[],training:['Power BI'],status:'Borrador',date:'2026-07-17'}
];
const content=document.querySelector('#content');let editing=null;
function save(){localStorage.setItem(KEY,JSON.stringify(records))}function esc(s=''){return String(s).replace(/[&<>'"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x]))}
function setView(view){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelector('#crumb').textContent='Inicio / '+({dashboard:'Dashboard',collaborators:'Colaboradores',reports:'Reportes'}[view]||'Estudio');document.querySelector('#title').textContent=({dashboard:'Resumen ejecutivo',collaborators:'Gestión de colaboradores',reports:'Reportes y exportación',form:'Estudio socioeconómico'}[view]);if(view==='dashboard')dashboard();if(view==='collaborators')collaborators();if(view==='reports')reports();if(view==='form')form(editing)}
function dashboard(){let total=records.length,done=records.filter(r=>r.status==='Completada').length,avg=total?Math.round(records.reduce((a,r)=>a+Number(r.age),0)/total):0,credits=records.filter(r=>r.credits?.length).length,need=records.filter(r=>['Difícil','Muy difícil'].includes(r.economy)).length,depts={};records.forEach(r=>depts[r.department]=(depts[r.department]||0)+1);content.innerHTML=`<div class="actions"><p class="muted">Información para mejorar el bienestar del equipo.</p><button class="primary" onclick="newRecord()">+ Nuevo estudio</button></div><div class="cards">${[['♙',total,'Colaboradores registrados'],['✓',done,'Encuestas completadas'],['◷',avg+' años','Promedio de edad'],['▣',credits,'Personas con créditos'],['⌁',need,'Requieren apoyo financiero']].map(x=>`<div class="card"><i>${x[0]}</i><b>${x[1]}</b><span>${x[2]}</span></div>`).join('')}</div><div class="two"><div class="card"><h2>Colaboradores por departamento</h2>${Object.entries(depts).map(([n,v])=>`<div class="bar"><span>${esc(n)}</span><div><i style="width:${v/total*100}%"></i></div><b>${v}</b></div>`).join('')||'<p class="empty">Sin datos</p>'}</div><div class="card"><h2>Estudios recientes</h2>${records.slice(0,5).map(r=>`<p><b>${esc(r.name)}</b><br><small class="muted">${esc(r.department)} · ${esc(r.position)}</small></p>`).join('')}</div></div>`}
function collaborators(){content.innerHTML=`<div class="actions"><form class="search" onsubmit="event.preventDefault();findRecords(this.q.value)"><input name="q" placeholder="Buscar nombre, puesto o departamento"><button class="btn">Buscar</button></form><button class="primary" onclick="newRecord()">+ Nuevo colaborador</button></div><div class="card table">${table(records)}</div>`}
function table(rows){return `<table><thead><tr><th>Colaborador</th><th>Departamento</th><th>Puesto</th><th>Fecha</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${esc(r.name)}</b></td><td>${esc(r.department)}</td><td>${esc(r.position)}</td><td>${esc(r.date)}</td><td><span class="badge ${r.status==='Completada'?'done':'draft'}">${r.status}</span></td><td><button class="row-button" onclick="editRecord(${r.id})">Editar</button> <button class="row-button delete" onclick="removeRecord(${r.id})">Eliminar</button></td></tr>`).join('')}</tbody></table>${rows.length?'':'<p class="empty">No hay resultados.</p>'}`}
function findRecords(q){let x=q.toLowerCase();document.querySelector('.table').innerHTML=table(records.filter(r=>(r.name+r.department+r.position).toLowerCase().includes(x)))}
function newRecord(){editing=null;setView('form')}function editRecord(id){editing=records.find(r=>r.id===id);setView('form')}function removeRecord(id){if(confirm('¿Eliminar este registro?')){records=records.filter(r=>r.id!==id);save();collaborators()}}
function checked(group,items,old=[]){return `<div><h3>${group}</h3>${items.map(x=>`<label><input type="checkbox" name="${group}" value="${x}" ${old.includes(x)?'checked':''}>${x}</label>`).join('')}</div>`}
function form(r){r=r||{id:'',name:'',sex:'',age:'',department:'',position:'',housing:'',economy:'',debt:'',credits:[],training:[],date:new Date().toISOString().slice(0,10)};content.innerHTML=`<form class="form" onsubmit="storeRecord(event,${r.id||0})"><div class="card"><h2>Datos generales</h2><div class="form-grid"><label>Nombre completo*<input name="name" required value="${esc(r.name)}"></label><label>Sexo*<select name="sex" required><option>${esc(r.sex)}</option><option>Mujer</option><option>Hombre</option></select></label><label>Edad*<input name="age" type="number" min="18" required value="${esc(r.age)}"></label><label>Departamento*<input name="department" required value="${esc(r.department)}"></label><label>Puesto*<input name="position" required value="${esc(r.position)}"></label><label>Tipo de vivienda<input name="housing" value="${esc(r.housing)}" placeholder="Propia, Rentada, Infonavit"></label><label>Economía<select name="economy"><option>${esc(r.economy)}</option><option>Excelente</option><option>Buena</option><option>Regular</option><option>Difícil</option><option>Muy difícil</option></select></label><label>Deuda<select name="debt"><option>${esc(r.debt)}</option><option>Sin deuda</option><option>0-20%</option><option>21-40%</option><option>41-60%</option><option>Más de 60%</option></select></label></div></div><div class="card"><h2>Créditos y desarrollo</h2><div class="checks">${checked('credits',['Tarjetas de crédito','Automotriz','Hipotecario','Infonavit','Crédito personal'],r.credits)}${checked('training',['Ventas','Liderazgo','Power BI','Excel','Finanzas','Tecnología'],r.training)}<div><h3>Comentarios</h3><textarea name="comments" rows="7" placeholder="Observaciones relevantes"></textarea></div></div></div><div class="form-actions"><button type="button" class="btn" onclick="setView('collaborators')">Cancelar</button><button name="status" value="Borrador" class="btn">Guardar borrador</button><button name="status" value="Completada" class="primary">Finalizar estudio</button></div></form>`}
function storeRecord(e,id){e.preventDefault();let f=new FormData(e.target),status=e.submitter.value,obj={id:id||Date.now(),name:f.get('name'),sex:f.get('sex'),age:Number(f.get('age')),department:f.get('department'),position:f.get('position'),housing:f.get('housing'),economy:f.get('economy'),debt:f.get('debt'),credits:f.getAll('credits'),training:f.getAll('training'),status,date:new Date().toISOString().slice(0,10)};if(id)records=records.map(r=>r.id===id?obj:r);else records.unshift(obj);save();setView('collaborators')}
function reports(){content.innerHTML=`<div class="actions"><p class="muted">Exporta los registros para analizarlos en Excel.</p><button class="primary" onclick="downloadCSV()">⇩ Exportar CSV</button></div><div class="two"><div class="card"><h2>Registros</h2><p style="font-size:34px;font-weight:bold">${records.length}</p><p class="muted">Estudios registrados</p></div><div class="card"><h2>Uso sin servidor</h2><p class="muted">Los datos se conservan en este navegador. Para datos compartidos entre usuarios utiliza la versión PHP + MySQL.</p></div></div>`}
function downloadCSV(){let rows=[['Nombre','Sexo','Edad','Departamento','Puesto','Vivienda','Economía','Deuda','Estado','Fecha'],...records.map(r=>[r.name,r.sex,r.age,r.department,r.position,r.housing,r.economy,r.debt,r.status,r.date])],csv=rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='reporte-bienestar.csv';a.click()}
const loginScreen=document.querySelector('#login'),appScreen=document.querySelector('#app');
document.querySelector('#login-form').onsubmit=e=>{e.preventDefault();if(document.querySelector('#email').value==='admin@empresa.com'&&document.querySelector('#password').value==='admin123'){loginScreen.hidden=true;appScreen.hidden=false;dashboard()}else alert('Credenciales incorrectas')};document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelector('#logout').onclick=()=>{appScreen.hidden=true;loginScreen.hidden=false};

// Catálogo configurable basado en Cuestionario_Estudio_Socioeconomico.xlsx.
const QUESTION_KEY='bienestar-question-catalog';
const defaults=[
['Datos Generales','Nombre','Texto',''],['Datos Generales','Sexo','Opción','Masculino;Femenino;Prefiero no decir'],['Datos Generales','Edad','Número',''],['Datos Generales','Estado civil','Opción','Soltero;Casado;Unión libre;Divorciado;Viudo'],['Datos Generales','Escolaridad','Opción','Primaria;Secundaria;Preparatoria;Técnica;Licenciatura;Posgrado'],['Datos Generales','Departamento','Texto',''],['Datos Generales','Puesto','Texto',''],['Datos Generales','Antigüedad','Texto',''],['Datos Generales','Teléfono','Texto',''],['Datos Generales','Correo','Texto',''],
['Familia','Dependientes económicos','Número',''],['Familia','Personas que viven en casa','Número',''],['Familia','Ingreso familiar','Texto',''],['Familia','Otro ingreso','Sí/No',''],
['Vivienda','Tipo de vivienda','Opción','Propia;Rentada;Prestada;Infonavit'],['Vivienda','Material predominante','Texto',''],['Vivienda','Servicios con los que cuenta','Selección múltiple','Agua;Luz;Drenaje;Internet;Gas'],['Vivienda','Número de habitaciones','Número',''],
['Transporte','¿Cómo llega al trabajo?','Opción','Auto;Moto;Transporte público;Bicicleta;Caminando;Otro'],['Transporte','Tiempo de traslado','Opción','<15;15-30;31-60;>60 min'],['Transporte','Costo mensual de transporte','Número',''],['Transporte','¿Cuenta con vehículo propio?','Sí/No',''],
['Salud','Servicio médico','Opción','IMSS;ISSSTE;Privado;Otro;Ninguno'],['Salud','Enfermedades relevantes','Texto',''],['Salud','¿Tiene alguna discapacidad?','Sí/No',''],['Salud','Estado de salud','Opción','Excelente;Bueno;Regular;Malo'],
['Economía','¿Cómo considera su economía?','Opción','Excelente;Buena;Regular;Difícil;Muy difícil'],['Economía','¿Ahorra?','Sí/No',''],['Economía','Monto aproximado de ahorro','Texto',''],
['Créditos','¿Qué créditos tiene?','Selección múltiple','Tarjeta;Automotriz;Hipotecario;Infonavit;Personal;Nómina;Caja de ahorro'],['Créditos','Porcentaje destinado al pago de deudas','Opción','Sin deuda;0-20%;21-40%;41-60%;>60%'],['Créditos','¿Con qué frecuencia tiene dificultades para terminar el mes?','Opción','Nunca;Rara vez;Algunas veces;Frecuentemente;Siempre'],['Créditos','¿Cuenta con ahorro para emergencias?','Sí/No',''],['Créditos','Beneficios financieros de interés','Selección múltiple','Caja de ahorro;Educación financiera;Préstamos;Fondo de ahorro;Seguro médico;Seguro de vida;Apoyo escolar;Apoyo vivienda;Vales;Otro'],
['Desarrollo','Capacitaciones de interés','Selección múltiple','Ventas;Liderazgo;Power BI;Excel;Finanzas;Tecnología;Atención al cliente;Desarrollo personal;Otro'],['Comentarios','Comentarios adicionales','Texto largo','']
];
let questions=JSON.parse(localStorage.getItem(QUESTION_KEY)||'null')||defaults.map((q,i)=>({id:'q'+(i+1),section:q[0],label:q[1],type:q[2],options:q[3],active:true}));
function saveQuestions(){localStorage.setItem(QUESTION_KEY,JSON.stringify(questions))}function inputType(t){return t==='Número'?'number':t==='Texto largo'?'textarea':'text'}function opts(q){return q.options?q.options.split(';').filter(Boolean):[]}
function setView(view){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const names={dashboard:'Dashboard',collaborators:'Colaboradores',reports:'Reportes',catalog:'Catálogo de preguntas',form:'Estudio socioeconómico'};document.querySelector('#crumb').textContent='Inicio / '+names[view];document.querySelector('#title').textContent=names[view]==='Dashboard'?'Resumen ejecutivo':names[view];if(view==='dashboard')dashboard();if(view==='collaborators')collaborators();if(view==='reports')reports();if(view==='catalog')catalog();if(view==='form')form(editing)}
function newRecord(){editing=null;setView('form')}function editRecord(id){editing=records.find(r=>r.id===id);setView('form')}
function form(record){const answers=record?.answers||{};let last='';const fields=questions.filter(q=>q.active).map(q=>{let head=q.section!==last?`<h2 class="section-title">${esc(q.section)}</h2>`:'';last=q.section;let value=answers[q.id]??'';let control='';if(q.type==='Opción'||q.type==='Sí/No'){let choices=q.type==='Sí/No'?['Sí','No']:opts(q);control=`<select name="${q.id}"><option value="">Selecciona una opción</option>${choices.map(o=>`<option ${value===o?'selected':''}>${esc(o)}</option>`).join('')}</select>`}else if(q.type==='Selección múltiple'){const selected=Array.isArray(value)?value:[];control=`<div class="multi">${opts(q).map(o=>`<label><input type="checkbox" name="${q.id}" value="${esc(o)}" ${selected.includes(o)?'checked':''}>${esc(o)}</label>`).join('')}</div>`}else if(q.type==='Texto largo'){control=`<textarea name="${q.id}" rows="4">${esc(value)}</textarea>`}else{control=`<input name="${q.id}" type="${inputType(q.type)}" value="${esc(value)}">`}return head+`<div class="question"><span>${esc(q.label)}</span>${control}</div>`}).join('');content.innerHTML=`<form class="form" onsubmit="saveStudy(event,${record?.id||0})"><div class="card"><p class="muted">Las preguntas marcadas como activas en el catálogo forman este cuestionario.</p>${fields}</div><div class="form-actions"><button type="button" class="btn" onclick="setView('collaborators')">Cancelar</button><button name="status" value="Borrador" class="btn">Guardar borrador</button><button name="status" value="Completada" class="primary">Finalizar estudio</button></div></form>`}
function saveStudy(e,id){e.preventDefault();const f=new FormData(e.target),answers={};questions.filter(q=>q.active).forEach(q=>answers[q.id]=q.type==='Selección múltiple'?f.getAll(q.id):f.get(q.id));const find=(label)=>answers[questions.find(q=>q.label===label)?.id]||'';const record={id:id||Date.now(),answers,name:find('Nombre'),sex:find('Sexo'),age:Number(find('Edad'))||0,department:find('Departamento'),position:find('Puesto'),housing:find('Tipo de vivienda'),economy:find('¿Cómo considera su economía?'),debt:find('Porcentaje destinado al pago de deudas'),credits:find('¿Qué créditos tiene?')||[],training:find('Capacitaciones de interés')||[],status:e.submitter.value,date:new Date().toISOString().slice(0,10)};if(!record.name||!record.department||!record.position){alert('Completa al menos Nombre, Departamento y Puesto.');return}records=id?records.map(r=>r.id===id?record:r):[record,...records];save();setView('collaborators')}
function catalog(){content.innerHTML=`<div class="actions"><p class="muted">Activa, desactiva o agrega preguntas. Los cambios se reflejan de inmediato en el cuestionario.</p><div><a class="btn" href="assets/Plantilla_Cuestionario_CR3.xlsx" download>⇩ Descargar plantilla Excel</a> <button class="primary" onclick="addQuestion()">+ Nueva pregunta</button></div></div><div class="card"><div class="catalog-row"><b>Sección</b><b>Pregunta</b><b>Tipo</b><b>Opciones</b><b>Acción</b></div>${questions.map(q=>`<div class="catalog-row"><span>${esc(q.section)}</span><span>${esc(q.label)}</span><small>${esc(q.type)}</small><small>${esc(q.options||'—')}</small><div class="catalog-actions"><button class="link-button" onclick="toggleQuestion('${q.id}')">${q.active?'Dar de baja':'Activar'}</button><button class="link-button danger" onclick="deleteQuestion('${q.id}')">Eliminar</button></div></div>`).join('')}</div>`}
function addQuestion(){const section=prompt('Sección de la pregunta:');if(!section)return;const label=prompt('Pregunta:');if(!label)return;const type=prompt('Tipo: Texto, Texto largo, Número, Opción, Selección múltiple o Sí/No','Texto')||'Texto';const options=/Opción|Selección múltiple/.test(type)?prompt('Opciones separadas por punto y coma:')||'':'';questions.push({id:'custom-'+Date.now(),section,label,type,options,active:true});saveQuestions();catalog()}function toggleQuestion(id){questions=questions.map(q=>q.id===id?{...q,active:!q.active}:q);saveQuestions();catalog()}function deleteQuestion(id){if(confirm('¿Eliminar definitivamente esta pregunta?')){questions=questions.filter(q=>q.id!==id);saveQuestions();catalog()}}
function reports(){content.innerHTML=`<div class="actions"><p class="muted">Descarga los registros capturados o la plantilla editable del cuestionario.</p><div><a class="btn" href="assets/Plantilla_Cuestionario_CR3.xlsx" download>⇩ Plantilla de preguntas</a> <button class="primary" onclick="downloadCSV()">⇩ Exportar respuestas CSV</button></div></div><div class="two"><div class="card"><h2>Registros capturados</h2><p style="font-size:34px;font-weight:bold">${records.length}</p><p class="muted">Estudios disponibles para exportación.</p></div><div class="card"><h2>Plantilla Excel</h2><p class="muted">Incluye las 36 preguntas del cuestionario socioeconómico, sus secciones, tipo de respuesta y opciones. Puedes conservarla como respaldo o usarla para revisar el catálogo.</p><a class="btn" href="assets/Plantilla_Cuestionario_CR3.xlsx" download>Descargar plantilla .xlsx</a></div></div>`}

// Persistencia compartida en Supabase. Los cambios locales se envían a la nube.
const cloud = window.supabase.createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY);
let cloudReady = false;
async function loadCloudData(){
  const [studies, catalogRows] = await Promise.all([
    cloud.from('estudios_registros').select('payload').order('updated_at',{ascending:false}),
    cloud.from('estudios_catalogo').select('payload').order('updated_at',{ascending:true})
  ]);
  if(studies.error || catalogRows.error){alert('No se pudo conectar con la base de datos. Ejecuta primero supabase-schema.sql en Supabase.');console.error(studies.error || catalogRows.error);return false}
  records=studies.data.map(row=>row.payload);
  if(catalogRows.data.length) questions=catalogRows.data.map(row=>row.payload);
  else await syncCatalog();
  cloudReady=true;return true;
}
async function syncRecords(){if(!cloudReady)return;const rows=records.map(r=>({id:String(r.id),payload:r,updated_at:new Date().toISOString()}));if(rows.length){const {error}=await cloud.from('estudios_registros').upsert(rows);if(error){console.error(error);alert('No se pudo guardar el estudio en la nube.')}}}
async function syncCatalog(){const rows=questions.map(q=>({id:String(q.id),payload:q,updated_at:new Date().toISOString()}));if(rows.length){const {error}=await cloud.from('estudios_catalogo').upsert(rows);if(error)console.error(error)}}
function save(){localStorage.setItem(KEY,JSON.stringify(records));void syncRecords()}
function saveQuestions(){localStorage.setItem(QUESTION_KEY,JSON.stringify(questions));void syncCatalog()}
function removeRecord(id){if(confirm('¿Eliminar este registro?')){records=records.filter(r=>r.id!==id);save();void cloud.from('estudios_registros').delete().eq('id',String(id));collaborators()}}
function deleteQuestion(id){if(confirm('¿Eliminar definitivamente esta pregunta?')){questions=questions.filter(q=>q.id!==id);saveQuestions();void cloud.from('estudios_catalogo').delete().eq('id',String(id));catalog()}}
document.querySelector('#login-form').onsubmit=async e=>{e.preventDefault();if(document.querySelector('#email').value!=='admin@empresa.com'||document.querySelector('#password').value!=='admin123'){alert('Credenciales incorrectas');return}const ok=await loadCloudData();if(ok){loginScreen.hidden=true;appScreen.hidden=false;dashboard()}};
