const KEY='bienestar-html-records';
let records=JSON.parse(localStorage.getItem(KEY)||'null')||[
 {id:1,name:'Mariana López',sex:'Mujer',age:31,department:'Ventas',position:'Ejecutiva comercial',housing:'Propia',economy:'Buena',debt:'21-40%',credits:['Tarjeta'],training:['Liderazgo'],status:'Completada',date:'2026-07-16'},
 {id:2,name:'Carlos Ramírez',sex:'Hombre',age:42,department:'Operaciones',position:'Supervisor',housing:'Infonavit',economy:'Regular',debt:'41-60%',credits:['Infonavit'],training:['Excel'],status:'Completada',date:'2026-07-15'},
 {id:3,name:'Sofía Hernández',sex:'Mujer',age:26,department:'Tecnología',position:'Analista',housing:'Rentada',economy:'Buena',debt:'0-20%',credits:[],training:['Power BI'],status:'Borrador',date:'2026-07-17'}
];
const content=document.querySelector('#content');let editing=null;
function save(){localStorage.setItem(KEY,JSON.stringify(records))}function esc(s=''){return String(s).replace(/[&<>'"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x]))}
function setView(view){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelector('#crumb').textContent='Inicio / '+({dashboard:'Dashboard',collaborators:'Colaboradores',reports:'Reportes'}[view]||'Estudio');document.querySelector('#title').textContent=({dashboard:'Resumen ejecutivo',collaborators:'Gestión de colaboradores',reports:'Reportes y exportación',form:'Estudio socioeconómico'}[view]);if(view==='dashboard')dashboard();if(view==='collaborators')collaborators();if(view==='reports')reports();if(view==='form')form(editing)}
function dashboard(){let total=records.length,done=records.filter(r=>r.status==='Completada').length,avg=total?Math.round(records.reduce((a,r)=>a+Number(r.age),0)/total):0,credits=records.filter(r=>r.credits?.length).length,need=records.filter(r=>['Difícil','Muy difícil'].includes(r.economy)).length,depts={};records.forEach(r=>depts[r.department]=(depts[r.department]||0)+1);content.innerHTML=`<div class="actions"><p class="muted">Información para mejorar el bienestar del equipo.</p><button class="primary" onclick="newRecord()">+ Nuevo estudio</button></div><div class="cards">${[['♙',total,'Colaboradores registrados'],['✓',done,'Encuestas completadas'],['◷',avg+' años','Promedio de edad'],['▣',credits,'Personas con créditos'],['⌁',need,'Requieren apoyo financiero']].map(x=>`<div class="card"><i>${x[0]}</i><b>${x[1]}</b><span>${x[2]}</span></div>`).join('')}</div><div class="two"><div class="card"><h2>Colaboradores por departamento</h2>${Object.entries(depts).map(([n,v])=>`<div class="bar"><span>${esc(n)}</span><div><i style="width:${v/total*100}%"></i></div><b>${v}</b></div>`).join('')||'<p class="empty">Sin datos</p>'}</div><div class="card"><h2>Estudios recientes</h2>${records.slice(0,5).map(r=>`<p><b>${esc(r.name)}</b><br><small class="muted">${esc(r.department)} · ${esc(r.position)}</small></p>`).join('')}</div></div>`}
function collaborators(){content.innerHTML=`<div class="actions"><form class="search" onsubmit="event.preventDefault();findRecords(this.q.value)"><input name="q" placeholder="Buscar nombre, puesto o departamento"><button class="btn">Buscar</button></form><button class="primary" onclick="newRecord()">+ Nuevo colaborador</button></div><div class="card table">${table(records)}</div>`}
function table(rows){return `<table><thead><tr><th>Colaborador</th><th>Departamento</th><th>Puesto</th><th>Fecha</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${esc(r.name)}</b></td><td>${esc(r.department)}</td><td>${esc(r.position)}</td><td>${esc(r.date)}</td><td><span class="badge ${r.status==='Completada'?'done':'draft'}">${r.status}</span></td><td><button class="row-button" onclick="editRecord(${r.id})">Editar</button> <button class="row-button delete" onclick="removeRecord(${r.id})">Eliminar</button></td></tr>`).join('')}</tbody></table>${rows.length?'':'<p class="empty">No hay resultados.</p>'}`}
function findRecords(q){let x=q.toLowerCase();document.querySelector('.table').innerHTML=table(records.filter(r=>(r.name+r.department+r.position).toLowerCase().includes(x)))}
function newRecord(){editing=null;setView('form')}function editRecord(id){editing=records.find(r=>r.id===id);setView('form')}function removeRecord(id){if(confirm('¿Eliminar este registro?')){records=records.filter(r=>r.id!==id);save();collaborators()}}
function checked(group,items,old=[]){return `<div><h3>${group}</h3>${items.map(x=>`<label><input type="checkbox" name="${group}" value="${x}" ${old.includes(x)?'checked':''}>${x}</label>`).join('')}</div>`}
function form(r){r=r||{id:'',name:'',sex:'',age:'',department:'',position:'',housing:'',economy:'',debt:'',credits:[],training:[],date:new Date().toISOString().slice(0,10)};content.innerHTML=`<form class="form" onsubmit="storeRecord(event,${r.id||0})"><div class="card"><h2>Datos generales</h2><div class="form-grid"><label>Nombre completo*<input name="name" required value="${esc(r.name)}"></label><label>Sexo*<select name="sex" required><option>${esc(r.sex)}</option><option>Mujer</option><option>Hombre</option></select></label><label>Edad*<input name="age" type="number" min="18" required value="${esc(r.age)}"></label><label>Departamento*<input name="department" required value="${esc(r.department)}"></label><label>Puesto*<input name="position" required value="${esc(r.position)}"></label><label>Tipo de vivienda<input name="housing" value="${esc(r.housing)}" placeholder="Propia, Rentada, Infonavit"></label><label>Economía<select name="economy"><option>${esc(r.economy)}</option><option>Excelente</option><option>Buena</option><option>Regular</option><option>Difícil</option><option>Muy difícil</option></select></label><label>Deuda<select name="debt"><option>${esc(r.debt)}</option><option>Sin deuda</option><option>0-20%</option><option>21-40%</option><option>41-60%</option><option>Más de 60%</option></select></label></div></div><div class="card"><h2>Créditos y desarrollo</h2><div class="checks">${checked('credits',['Tarjetas de crédito','Automotriz','Hipotecario','Infonavit','Crédito personal'],r.credits)}${checked('training',['Ventas','Liderazgo','Power BI','Excel','Finanzas','Tecnología'],r.training)}<div><h3>Comentarios</h3><textarea name="comments" rows="7" placeholder="Observaciones relevantes"></textarea></div></div></div><div class="form-actions"><button type="button" class="btn" onclick="setView('collaborators')">Cancelar</button><button name="status" value="Borrador" class="btn">Guardar borrador</button><button name="status" value="Completada" class="primary">Finalizar estudio</button></div></form>`}
function storeRecord(e,id){e.preventDefault();let f=new FormData(e.target),status=e.submitter.value,obj={id:id||Date.now(),name:f.get('name'),sex:f.get('sex'),age:Number(f.get('age')),department:f.get('department'),position:f.get('position'),housing:f.get('housing'),economy:f.get('economy'),debt:f.get('debt'),credits:f.getAll('credits'),training:f.getAll('training'),status,date:new Date().toISOString().slice(0,10)};if(id)records=records.map(r=>r.id===id?obj:r);else records.unshift(obj);save();setView('collaborators')}
function reports(){content.innerHTML=`<div class="actions"><p class="muted">Exporta los registros para analizarlos en Excel.</p><button class="primary" onclick="downloadCSV()">⇩ Exportar CSV</button></div><div class="two"><div class="card"><h2>Registros</h2><p style="font-size:34px;font-weight:bold">${records.length}</p><p class="muted">Estudios registrados</p></div><div class="card"><h2>Uso sin servidor</h2><p class="muted">Los datos se conservan en este navegador. Para datos compartidos entre usuarios utiliza la versión PHP + MySQL.</p></div></div>`}
function downloadCSV(){let rows=[['Nombre','Sexo','Edad','Departamento','Puesto','Vivienda','Economía','Deuda','Estado','Fecha'],...records.map(r=>[r.name,r.sex,r.age,r.department,r.position,r.housing,r.economy,r.debt,r.status,r.date])],csv=rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='reporte-bienestar.csv';a.click()}
const loginScreen=document.querySelector('#login'),appScreen=document.querySelector('#app');
document.querySelector('#login-form').onsubmit=e=>{e.preventDefault();if(document.querySelector('#email').value==='admin@empresa.com'&&document.querySelector('#password').value==='admin123'){loginScreen.hidden=true;appScreen.hidden=false;dashboard()}else alert('Credenciales incorrectas')};document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelector('#logout').onclick=()=>{appScreen.hidden=true;loginScreen.hidden=false};

// Catálogo configurable basado en Cuestionario_Estudio_Socioeconomico.xlsx.
const QUESTION_KEY='bienestar-question-catalog';
const defaults=[
['Datos Generales','Nombre','Texto',''],['Datos Generales','Sexo','Opción','Masculino;Femenino;Prefiero no decir'],['Datos Generales','Edad','Número',''],['Datos Generales','Estado civil','Opción','Soltero;Casado;Unión libre;Divorciado;Viudo'],['Datos Generales','Escolaridad','Opción','Primaria;Secundaria;Preparatoria;Técnica;Licenciatura;Posgrado'],['Datos Generales','Departamento','Texto',''],['Datos Generales','Puesto','Texto',''],['Datos Generales','Antigüedad','Texto',''],['Datos Generales','Teléfono','Texto',''],['Datos Generales','Correo','Texto',''],
['Familia','Dependientes económicos','Número',''],['Familia','Personas que viven en casa','Número',''],['Familia','Ingreso familiar','Texto',''],['Familia','Otro ingreso','Sí/No',''],
['Vivienda','Tipo de vivienda','Opción','Propia;Rentada;Prestada;Infonavit'],['Vivienda','Material predominante','Texto',''],['Vivienda','Servicios con los que cuenta','Selección múltiple','Agua;Luz;Drenaje;Internet;Gas'],['Vivienda','Número de habitaciones','Número',''],
['Transporte','¿Cómo llega al trabajo?','Opción','Auto;Moto;Transporte público;Bicicleta;Caminando;Otro'],['Transporte','Tiempo de traslado','Opción','<15;15-30;31-60;>60 min'],['Transporte','Costo mensual de transporte','Número',''],['Transporte','¿Cuenta con vehículo propio?','Sí/No',''],
['Salud','Servicio médico','Opción','IMSS;ISSSTE;Privado;Otro;Ninguno'],['Salud','Enfermedades relevantes','Texto',''],['Salud','¿Tiene alguna discapacidad?','Sí/No',''],['Salud','Estado de salud','Opción','Excelente;Bueno;Regular;Malo'],
['Economía','¿Cómo considera su economía?','Opción','Excelente;Buena;Regular;Difícil;Muy difícil'],['Economía','¿Ahorra?','Sí/No',''],['Economía','Monto aproximado de ahorro','Texto',''],
['Créditos','¿Qué créditos tiene?','Selección múltiple','Tarjeta;Automotriz;Hipotecario;Infonavit;Personal;Nómina;Caja de ahorro'],['Créditos','Porcentaje destinado al pago de deudas','Opción','Sin deuda;0-20%;21-40%;41-60%;>60%'],['Créditos','¿Con qué frecuencia tiene dificultades para terminar el mes?','Opción','Nunca;Rara vez;Algunas veces;Frecuentemente;Siempre'],['Créditos','¿Cuenta con ahorro para emergencias?','Sí/No',''],['Créditos','Beneficios financieros de interés','Selección múltiple','Caja de ahorro;Educación financiera;Préstamos;Fondo de ahorro;Seguro médico;Seguro de vida;Apoyo escolar;Apoyo vivienda;Vales;Otro'],
['Desarrollo','Capacitaciones de interés','Selección múltiple','Ventas;Liderazgo;Power BI;Excel;Finanzas;Tecnología;Atención al cliente;Desarrollo personal;Otro'],['Comentarios','Comentarios adicionales','Texto largo','']
];
let questions=JSON.parse(localStorage.getItem(QUESTION_KEY)||'null')||defaults.map((q,i)=>({id:'q'+(i+1),section:q[0],label:q[1],type:q[2],options:q[3],active:true}));
function saveQuestions(){localStorage.setItem(QUESTION_KEY,JSON.stringify(questions))}function inputType(t){return t==='Número'?'number':t==='Texto largo'?'textarea':'text'}function opts(q){return q.options?q.options.split(';').filter(Boolean):[]}
function setView(view){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const names={dashboard:'Dashboard',collaborators:'Colaboradores',reports:'Reportes',catalog:'Catálogo de preguntas',form:'Estudio socioeconómico'};document.querySelector('#crumb').textContent='Inicio / '+names[view];document.querySelector('#title').textContent=names[view]==='Dashboard'?'Resumen ejecutivo':names[view];if(view==='dashboard')dashboard();if(view==='collaborators')collaborators();if(view==='reports')reports();if(view==='catalog')catalog();if(view==='form')form(editing)}
function newRecord(){editing=null;setView('form')}function editRecord(id){editing=records.find(r=>r.id===id);setView('form')}
function isHouseholdCountQuestion(label){return label==='Personas que viven en casa'||label==='¿Cuántas personas viven actualmente en el domicilio?'}
function householdMembersTable(count,members=[]){const rows=Math.max(0,Number(count)||0);const relationship=['Padre','Madre','Esposo(a)','Hijo(a)','Hermano(a)','Abuelo(a)','Otro'];const employment=['Formal','Informal','Independiente','Negocio propio','Eventual','Desempleado'];return `<div id="household-members-table" class="household-table-wrap">${rows?`<p class="household-table-title">Integrantes del hogar</p><div class="table"><table class="household-table"><thead><tr><th>N.° de integrante</th><th>Nombre del integrante</th><th>Parentesco</th><th>Edad</th><th>¿El integrante trabaja actualmente?</th><th>Ocupación</th><th>Tipo de empleo del integrante</th><th>Ingreso mensual</th></tr></thead><tbody>${Array.from({length:rows},(_,index)=>{const member=members[index]||{};return `<tr data-household-row="${index}"><td><b>${index+1}</b></td><td><input data-field="name" value="${esc(member.name||'')}"></td><td><select data-field="relationship"><option value="">Selecciona</option>${relationship.map(option=>`<option value="${esc(option)}" ${member.relationship===option?'selected':''}>${esc(option)}</option>`).join('')}</select></td><td><input data-field="age" type="number" min="0" value="${esc(member.age||'')}"></td><td><select data-field="works"><option value="">Selecciona</option><option value="Sí" ${member.works==='Sí'?'selected':''}>Sí</option><option value="No" ${member.works==='No'?'selected':''}>No</option></select></td><td><input data-field="occupation" value="${esc(member.occupation||'')}"></td><td><select data-field="employmentType"><option value="">Selecciona</option>${employment.map(option=>`<option value="${esc(option)}" ${member.employmentType===option?'selected':''}>${esc(option)}</option>`).join('')}</select></td><td><input data-field="monthlyIncome" type="number" min="0" step="0.01" value="${esc(member.monthlyIncome||'')}"></td></tr>`}).join('')}</tbody></table></div>`:'<p class="muted household-empty">Captura el número de personas para habilitar la tabla de integrantes.</p>'}</div>`}
function readHouseholdMembers(){return [...document.querySelectorAll('[data-household-row]')].map(row=>Object.fromEntries([...row.querySelectorAll('[data-field]')].map(field=>[field.dataset.field,field.value])))}
function syncHouseholdRows(value){const container=document.querySelector('#household-members-table');if(container)container.outerHTML=householdMembersTable(value,readHouseholdMembers())}
function form(record){const answers=record?.answers||{};let last='';const fields=questions.filter(q=>q.active).map(q=>{let head=q.section!==last?`<h2 class="section-title">${esc(q.section)}</h2>`:'';last=q.section;let value=answers[q.id]??'';let control='';if(q.type==='Opción'||q.type==='Sí/No'){let choices=q.type==='Sí/No'?['Sí','No']:opts(q);control=`<select name="${q.id}"><option value="">Selecciona una opción</option>${choices.map(o=>`<option ${value===o?'selected':''}>${esc(o)}</option>`).join('')}</select>`}else if(q.type==='Selección múltiple'){const selected=Array.isArray(value)?value:[];control=`<div class="multi">${opts(q).map(o=>`<label><input type="checkbox" name="${q.id}" value="${esc(o)}" ${selected.includes(o)?'checked':''}>${esc(o)}</label>`).join('')}</div>`}else if(q.type==='Texto largo'){control=`<textarea name="${q.id}" rows="4">${esc(value)}</textarea>`}else{control=`<input name="${q.id}" type="${inputType(q.type)}" value="${esc(value)}" ${isHouseholdCountQuestion(q.label)?'oninput="syncHouseholdRows(this.value)"':''}>`}const household=isHouseholdCountQuestion(q.label)?householdMembersTable(value,answers.householdMembers||[]):'';return head+`<div class="question"><span>${esc(q.label)}</span>${control}${household}</div>`}).join('');content.innerHTML=`<form class="form" onsubmit="saveStudy(event,${record?.id||0})"><div class="card"><p class="muted">Las preguntas marcadas como activas en el catálogo forman este cuestionario.</p>${fields}</div><div class="form-actions"><button type="button" class="btn" onclick="setView('collaborators')">Cancelar</button><button name="status" value="Borrador" class="btn">Guardar borrador</button><button name="status" value="Completada" class="primary">Finalizar estudio</button></div></form>`}
function saveStudy(e,id){e.preventDefault();const f=new FormData(e.target),answers={};questions.filter(q=>q.active).forEach(q=>answers[q.id]=q.type==='Selección múltiple'?f.getAll(q.id):f.get(q.id));answers.householdMembers=readHouseholdMembers();const find=(label)=>answers[questions.find(q=>q.label===label)?.id]||'';const record={id:id||Date.now(),ownerId:currentProfile?.id||editing?.ownerId||'',answers,name:find('Nombre'),sex:find('Sexo'),age:Number(find('Edad'))||0,department:find('Departamento'),position:find('Puesto'),housing:find('Tipo de vivienda'),economy:find('¿Cómo considera su economía?'),debt:find('Porcentaje destinado al pago de deudas'),credits:find('¿Qué créditos tiene?')||[],training:find('Capacitaciones de interés')||[],status:e.submitter.value,date:new Date().toISOString().slice(0,10)};if(!record.name||!record.department||!record.position){alert('Completa al menos Nombre, Departamento y Puesto.');return}records=id?records.map(r=>r.id===id?record:r):[record,...records];save();setView(currentProfile?.role==='RESPONDENT'?'form':'collaborators')}
function catalog(){content.innerHTML=`<div class="actions"><p class="muted">Activa, desactiva o agrega preguntas. Los cambios se reflejan de inmediato en el cuestionario.</p><div><a class="btn" href="assets/Plantilla_Cuestionario_CR3.xlsx" download>⇩ Descargar plantilla Excel</a> <button class="primary" onclick="addQuestion()">+ Nueva pregunta</button></div></div><div class="card"><div class="catalog-row"><b>Sección</b><b>Pregunta</b><b>Tipo</b><b>Opciones</b><b>Acción</b></div>${questions.map(q=>`<div class="catalog-row"><span>${esc(q.section)}</span><span>${esc(q.label)}</span><small>${esc(q.type)}</small><small>${esc(q.options||'—')}</small><div class="catalog-actions"><button class="link-button" onclick="toggleQuestion('${q.id}')">${q.active?'Dar de baja':'Activar'}</button><button class="link-button danger" onclick="deleteQuestion('${q.id}')">Eliminar</button></div></div>`).join('')}</div>`}
function addQuestion(){const section=prompt('Sección de la pregunta:');if(!section)return;const label=prompt('Pregunta:');if(!label)return;const type=prompt('Tipo: Texto, Texto largo, Número, Opción, Selección múltiple o Sí/No','Texto')||'Texto';const options=/Opción|Selección múltiple/.test(type)?prompt('Opciones separadas por punto y coma:')||'':'';questions.push({id:'custom-'+Date.now(),section,label,type,options,active:true});saveQuestions();catalog()}function toggleQuestion(id){questions=questions.map(q=>q.id===id?{...q,active:!q.active}:q);saveQuestions();catalog()}function deleteQuestion(id){if(confirm('¿Eliminar definitivamente esta pregunta?')){questions=questions.filter(q=>q.id!==id);saveQuestions();catalog()}}
function reports(){content.innerHTML=`<div class="actions"><p class="muted">Descarga los registros capturados o la plantilla editable del cuestionario.</p><div><a class="btn" href="assets/Plantilla_Cuestionario_CR3.xlsx" download>⇩ Plantilla de preguntas</a> <button class="primary" onclick="downloadCSV()">⇩ Exportar respuestas CSV</button></div></div><div class="two"><div class="card"><h2>Registros capturados</h2><p style="font-size:34px;font-weight:bold">${records.length}</p><p class="muted">Estudios disponibles para exportación.</p></div><div class="card"><h2>Plantilla Excel</h2><p class="muted">Incluye las 36 preguntas del cuestionario socioeconómico, sus secciones, tipo de respuesta y opciones. Puedes conservarla como respaldo o usarla para revisar el catálogo.</p><a class="btn" href="assets/Plantilla_Cuestionario_CR3.xlsx" download>Descargar plantilla .xlsx</a></div></div>`}

// Persistencia compartida en Supabase. Los cambios locales se envían a la nube.
const cloud = window.supabase.createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY);
let cloudReady = false;
async function loadCloudData(){
  const [studies, catalogRows] = await Promise.all([
    cloud.from('estudios_registros').select('payload').order('updated_at',{ascending:false}),
    cloud.from('estudios_catalogo').select('payload').order('updated_at',{ascending:true})
  ]);
  if(studies.error || catalogRows.error){alert('No se pudo conectar con la base de datos. Ejecuta primero supabase-schema.sql en Supabase.');console.error(studies.error || catalogRows.error);return false}
  records=studies.data.map(row=>row.payload);
  if(catalogRows.data.length) questions=catalogRows.data.map(row=>row.payload);
  else await syncCatalog();
  cloudReady=true;return true;
}
async function syncRecords(){if(!cloudReady)return;const rows=records.map(r=>({id:String(r.id),payload:r,updated_at:new Date().toISOString()}));if(rows.length){const {error}=await cloud.from('estudios_registros').upsert(rows);if(error){console.error(error);alert('No se pudo guardar el estudio en la nube.')}}}
async function syncCatalog(){const rows=questions.map(q=>({id:String(q.id),payload:q,updated_at:new Date().toISOString()}));if(rows.length){const {error}=await cloud.from('estudios_catalogo').upsert(rows);if(error)console.error(error)}}
function save(){localStorage.setItem(KEY,JSON.stringify(records));void syncRecords()}
function saveQuestions(){localStorage.setItem(QUESTION_KEY,JSON.stringify(questions));void syncCatalog()}
function removeRecord(id){if(confirm('¿Eliminar este registro?')){records=records.filter(r=>r.id!==id);save();void cloud.from('estudios_registros').delete().eq('id',String(id));collaborators()}}
function deleteQuestion(id){if(confirm('¿Eliminar definitivamente esta pregunta?')){questions=questions.filter(q=>q.id!==id);saveQuestions();void cloud.from('estudios_catalogo').delete().eq('id',String(id));catalog()}}
document.querySelector('#login-form').onsubmit=async e=>{e.preventDefault();if(document.querySelector('#email').value!=='admin@empresa.com'||document.querySelector('#password').value!=='admin123'){alert('Credenciales incorrectas');return}const ok=await loadCloudData();if(ok){loginScreen.hidden=true;appScreen.hidden=false;dashboard()}};

// Usuarios reales y roles mediante Supabase Auth.
let currentProfile = null;
const apiHeaders = async () => { const { data } = await cloud.auth.getSession(); return { 'Content-Type':'application/json', Authorization:`Bearer ${data.session?.access_token || ''}` }; };
async function openApp(){
  const { data:{ user } } = await cloud.auth.getUser(); if(!user) return;
  const { data: profile, error } = await cloud.from('profiles').select('*').eq('id',user.id).single();
  if(error){document.querySelector('#login-message').textContent='Tu perfil aún no está listo. Contacta al administrador.';await cloud.auth.signOut();return;}
  currentProfile=profile;document.querySelector('#profile-name').textContent=profile.name||user.email;document.querySelector('#profile-role').textContent=profile.role==='ADMIN'?'Administrador':profile.role==='RESPONDENT'?'Encuestado':'Recursos Humanos';document.querySelector('#avatar').textContent=(profile.name||user.email)[0].toUpperCase();document.querySelector('#admin-nav').hidden=profile.role!=='ADMIN';
  document.querySelectorAll('[data-view="dashboard"],[data-view="collaborators"],[data-view="reports"],[data-view="catalog"]').forEach(item=>item.hidden=profile.role==='RESPONDENT');
  const ok=await loadCloudData();if(ok){loginScreen.hidden=true;appScreen.hidden=false;if(profile.role==='RESPONDENT'){editing=records.find(r=>r.ownerId===profile.id)||null;setView('form')}else dashboard()}
}
function setView(view){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const names={dashboard:'Dashboard',collaborators:'Colaboradores',reports:'Reportes',catalog:'Catálogo de preguntas',admin:'Administración de usuarios',form:'Estudio socioeconómico'};document.querySelector('#crumb').textContent='Inicio / '+names[view];document.querySelector('#title').textContent=names[view]==='Dashboard'?'Resumen ejecutivo':names[view];if(view==='dashboard')dashboard();if(view==='collaborators')collaborators();if(view==='reports')reports();if(view==='catalog')catalog();if(view==='admin')adminUsers();if(view==='form')form(editing)}
async function adminUsers(){if(currentProfile?.role!=='ADMIN'){alert('Solo el administrador puede gestionar usuarios.');setView('dashboard');return}content.innerHTML=`<div class="card"><h2>Agregar usuario</h2><form class="form-grid" onsubmit="createUser(event)"><label>Nombre<input name="name" required></label><label>Correo<input name="email" type="email" required></label><label>Contraseña temporal<input name="password" type="password" minlength="8" required></label><label>Rol<select name="role"><option value="HR">Recursos Humanos</option><option value="RESPONDENT">Encuestado (solo cuestionario)</option><option value="ADMIN">Administrador</option></select></label><div><button class="primary">Crear usuario</button></div></form></div><div class="card" style="margin-top:18px"><h2>Usuarios</h2><p class="muted">Cargando usuarios...</p></div>`;const response=await fetch('/api/admin/users',{headers:await apiHeaders()});const data=await response.json();if(!response.ok){content.innerHTML+=`<p class="empty">${esc(data.error||'No se pudieron cargar los usuarios.')}</p>`;return}const table=`<div class="card" style="margin-top:18px"><h2>Usuarios registrados</h2><div class="table"><table><thead><tr><th>Nombre</th><th>Correo</th><th>Rol</th><th>Acciones</th></tr></thead><tbody>${data.users.map(u=>`<tr><td>${esc(u.name||'Sin nombre')}</td><td>${esc(u.email)}</td><td><span class="badge ${u.role==='ADMIN'?'done':'draft'}">${u.role==='ADMIN'?'Administrador':u.role==='RESPONDENT'?'Encuestado':'RH'}</span></td><td><button class="row-button" onclick="resetUserPassword('${u.id}')">Resetear contraseña</button></td></tr>`).join('')}</tbody></table></div></div>`;content.innerHTML=content.innerHTML.replace(/<div class="card" style="margin-top:18px"><h2>Usuarios<\/h2>[\s\S]*?<\/div>/,table)}
async function createUser(e){e.preventDefault();const f=new FormData(e.target);const res=await fetch('/api/admin/users',{method:'POST',headers:await apiHeaders(),body:JSON.stringify(Object.fromEntries(f))});const data=await res.json();if(!res.ok){alert(data.error||'No se pudo crear el usuario.');return}alert('Usuario creado correctamente.');adminUsers()}
async function resetUserPassword(id){const password=prompt('Nueva contraseña temporal (mínimo 8 caracteres):');if(!password)return;const res=await fetch('/api/admin/users',{method:'PATCH',headers:await apiHeaders(),body:JSON.stringify({userId:id,password})});const data=await res.json();alert(res.ok?'Contraseña actualizada.':(data.error||'No se pudo actualizar.'))}
document.querySelector('#login-form').onsubmit=async e=>{e.preventDefault();const email=document.querySelector('#email').value,password=document.querySelector('#password').value;const { error }=await cloud.auth.signInWithPassword({email,password});if(error){document.querySelector('#login-message').textContent=error.message;return}await openApp()};
document.querySelector('#logout').onclick=async()=>{await cloud.auth.signOut();appScreen.hidden=true;loginScreen.hidden=false;document.querySelector('#password').value=''};
document.querySelector('#password-settings').onclick=async()=>{const password=prompt('Escribe tu nueva contraseña (mínimo 8 caracteres):');if(!password)return;if(password.length<8){alert('La contraseña debe tener al menos 8 caracteres.');return}const {error}=await cloud.auth.updateUser({password});alert(error?error.message:'Tu contraseña fue actualizada correctamente.')};
cloud.auth.getSession().then(({data})=>{if(data.session)openApp()});

// Catálogo: importación desde Excel/CSV y orden manual persistente.
async function loadCloudData(){
  const [studies, catalogRows] = await Promise.all([
    cloud.from('estudios_registros').select('payload').order('updated_at',{ascending:false}),
    cloud.from('estudios_catalogo').select('payload,sort_order').order('sort_order',{ascending:true})
  ]);
  if(studies.error || catalogRows.error){alert('No se pudo conectar con la base de datos. Ejecuta primero supabase-schema.sql en Supabase.');console.error(studies.error || catalogRows.error);return false}
  records=studies.data.map(row=>row.payload);
  if(catalogRows.data.length) questions=catalogRows.data.map(row=>row.payload);
  else if(currentProfile?.role==='ADMIN') await syncCatalog();
  cloudReady=true;return true;
}
async function syncCatalog(){const rows=questions.map((q,index)=>({id:String(q.id),payload:q,sort_order:index,updated_at:new Date().toISOString()}));if(rows.length){const {error}=await cloud.from('estudios_catalogo').upsert(rows);if(error)console.error(error)}}
function saveQuestions(){localStorage.setItem(QUESTION_KEY,JSON.stringify(questions));void syncCatalog()}
function catalog(){const editable=currentProfile?.role==='ADMIN';content.innerHTML=`<div class="actions"><p class="muted">Ordena las preguntas con las flechas o importa el formato Excel. Los cambios se reflejan en el cuestionario.</p><div>${editable?`<label class="btn" for="catalog-import">⇧ Importar Excel/CSV</label><input id="catalog-import" type="file" accept=".xlsx,.xls,.csv" hidden onchange="importCatalogFile(event)"> <a class="btn" href="assets/Plantilla_Cuestionario_CR3.xlsx" download>⇩ Plantilla</a> <button class="primary" onclick="addQuestion()">+ Nueva pregunta</button>`:`<a class="btn" href="assets/Plantilla_Cuestionario_CR3.xlsx" download>⇩ Plantilla</a>`}</div></div><div class="card"><div class="catalog-row"><b>Sección</b><b>Pregunta</b><b>Tipo</b><b>Opciones</b><b>Orden / acción</b></div>${questions.map((q,index)=>`<div class="catalog-row"><span>${esc(q.section)}</span><span>${esc(q.label)}</span><small>${esc(q.type)}</small><small>${esc(q.options||'—')}</small><div class="catalog-actions">${editable?`<button class="link-button" title="Subir" onclick="moveQuestion(${index},-1)">↑</button><button class="link-button" title="Bajar" onclick="moveQuestion(${index},1)">↓</button><button class="link-button" onclick="toggleQuestion('${q.id}')">${q.active?'Dar de baja':'Activar'}</button><button class="link-button danger" onclick="deleteQuestion('${q.id}')">Eliminar</button>`:'Solo lectura'}</div></div>`).join('')}</div>`}
function moveQuestion(index,direction){const target=index+direction;if(target<0||target>=questions.length)return;[questions[index],questions[target]]=[questions[target],questions[index]];saveQuestions();catalog()}
function normalizeHeader(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase()}
async function importCatalogFile(event){const file=event.target.files?.[0];if(!file)return;try{const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'});const sheet=workbook.Sheets[workbook.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(sheet,{header:1,defval:''});const headerIndex=rows.findIndex(row=>row.some(cell=>normalizeHeader(cell)==='pregunta'));if(headerIndex<0)throw new Error('No se encontró la columna Pregunta. Usa la plantilla descargable.');const headers=rows[headerIndex].map(normalizeHeader);const sectionIndex=headers.findIndex(h=>h==='seccion');const questionIndex=headers.findIndex(h=>h==='pregunta');const typeIndex=headers.findIndex(h=>h==='tipo');const optionsIndex=headers.findIndex(h=>h.startsWith('opciones'));const imported=rows.slice(headerIndex+1).filter(row=>String(row[questionIndex]||'').trim()).map((row,index)=>({id:`import-${Date.now()}-${index}`,section:String(row[sectionIndex]||'General').trim(),label:String(row[questionIndex]).trim(),type:['Texto','Texto largo','Número','Opción','Selección múltiple','Sí/No'].includes(String(row[typeIndex]).trim())?String(row[typeIndex]).trim():'Texto',options:String(row[optionsIndex]||'').trim(),active:true}));if(!imported.length)throw new Error('El archivo no contiene preguntas válidas.');if(!confirm(`Se reemplazarán las ${questions.length} preguntas actuales por ${imported.length} preguntas importadas. ¿Continuar?`))return;const oldIds=questions.map(q=>String(q.id));questions=imported;localStorage.setItem(QUESTION_KEY,JSON.stringify(questions));if(cloudReady&&oldIds.length)await cloud.from('estudios_catalogo').delete().in('id',oldIds);await syncCatalog();catalog();alert('Catálogo importado y ordenado correctamente.')}catch(error){alert(error.message||'No fue posible importar el archivo.');console.error(error)}finally{event.target.value=''}}

function dashboard(){const total=records.length, completed=records.filter(r=>r.status==='Completada').length, average=total?Math.round(records.reduce((sum,r)=>sum+(Number(r.age)||0),0)/total):0, financial=records.filter(r=>['Difícil','Muy difícil'].includes(r.economy)).length;const departments={};records.forEach(r=>departments[r.department||'Sin departamento']=(departments[r.department||'Sin departamento']||0)+1);const top=Object.entries(departments).sort((a,b)=>b[1]-a[1]).slice(0,4);content.innerHTML=`<section class="hero"><p class="eyebrow" style="color:#bfdbfe">SISTEMA INTEGRAL · GRUPO CR3 DRIVE</p><h2>Panorama de bienestar laboral</h2><p>Consulta los indicadores socioeconómicos de tu equipo y prioriza acciones de apoyo.</p><button class="primary" onclick="newRecord()">+ Nuevo estudio</button></section><div class="stat-grid"><div class="card stat-card"><b>${total}</b><span>Colaboradores registrados</span></div><div class="card stat-card"><b>${completed}</b><span>Estudios completados</span></div><div class="card stat-card"><b>${average} años</b><span>Promedio de edad</span></div><div class="card stat-card"><b>${financial}</b><span>Requieren apoyo financiero</span></div></div><div class="two"><div class="card"><h2>Distribución por departamento</h2>${top.map(([name,value])=>`<div class="bar"><span>${esc(name)}</span><div><i style="width:${total?value/total*100:0}%"></i></div><b>${value}</b></div>`).join('')||'<p class="empty">Aún no hay estudios registrados.</p>'}</div><div class="card"><h2>Insights de bienestar</h2><div class="insight"><i>✓</i><div><b>${completed} estudios finalizados</b><small>${total?Math.round(completed/total*100):0}% del total capturado.</small></div></div><div class="insight"><i>⌁</i><div><b>${records.filter(r=>r.credits?.length).length} personas con créditos</b><small>Identifica oportunidades de educación financiera.</small></div></div><div class="insight"><i>↗</i><div><b>${records.filter(r=>r.training?.length).length} personas con capacitación de interés</b><small>Información útil para el plan de desarrollo.</small></div></div></div></div>`}
function reports(){const total=records.length,completed=records.filter(r=>r.status==='Completada').length,credit=records.filter(r=>r.credits?.length).length,training=records.filter(r=>r.training?.length).length;content.innerHTML=`<section class="hero"><p class="eyebrow" style="color:#bfdbfe">REPORTES Y EXPORTACIÓN</p><h2>Información lista para decisiones</h2><p>Descarga los datos consolidados o revisa rápidamente las principales señales de bienestar.</p><button class="primary" onclick="downloadCSV()">⇩ Exportar respuestas CSV</button></section><div class="stat-grid"><div class="card stat-card"><b>${total}</b><span>Estudios disponibles</span></div><div class="card stat-card"><b>${completed}</b><span>Concluidos</span></div><div class="card stat-card"><b>${credit}</b><span>Con créditos vigentes</span></div><div class="card stat-card"><b>${training}</b><span>Con interés en capacitación</span></div></div><div class="two"><div class="card"><h2>Resumen de la información</h2><div class="report-kpi"><span class="muted">Avance de captura</span><strong>${total?Math.round(completed/total*100):0}%</strong></div><div class="bar"><span>Completadas</span><div><i style="width:${total?completed/total*100:0}%"></i></div><b>${completed}</b></div><div class="report-strip"><span class="report-pill">Créditos: ${credit}</span><span class="report-pill">Capacitación: ${training}</span><span class="report-pill">Pendientes: ${total-completed}</span></div></div><div class="card"><h2>Recursos disponibles</h2><p class="muted">Descarga la plantilla para revisar o importar el catálogo de preguntas.</p><a class="btn" href="assets/Plantilla_Cuestionario_CR3.xlsx" download>⇩ Plantilla de preguntas</a><button class="primary" style="margin-left:8px" onclick="downloadCSV()">Exportar CSV</button></div></div>`}
async function removeRecord(id){if(!confirm('¿Eliminar este registro de forma permanente?'))return;const previous=[...records];records=records.filter(r=>r.id!==id);localStorage.setItem(KEY,JSON.stringify(records));collaborators();const {error}=await cloud.from('estudios_registros').delete().eq('id',String(id));if(error){records=previous;localStorage.setItem(KEY,JSON.stringify(records));alert('No fue posible eliminar el estudio en Supabase: '+error.message);collaborators()}}
function roleName(role){return role==='ADMIN'?'Administrador':role==='RESPONDENT'?'Colaborador · solo cuestionario':'Recursos Humanos'}
async function adminUsers(){if(currentProfile?.role!=='ADMIN'){alert('Solo el administrador puede gestionar usuarios.');setView('dashboard');return}content.innerHTML=`<div class="card"><h2>Agregar usuario</h2><form class="form-grid" onsubmit="createUser(event)"><label>Nombre<input name="name" required></label><label>Correo<input name="email" type="email" required></label><label>Contraseña temporal<input name="password" type="password" minlength="8" required></label><label>Rol<select name="role"><option value="RH">Recursos Humanos</option><option value="RESPONDENT">Colaborador · solo cuestionario</option><option value="ADMIN">Administrador</option></select></label><div><button class="primary">Crear usuario</button></div></form></div><div class="card" style="margin-top:18px"><h2>Usuarios</h2><p class="muted">Cargando usuarios...</p></div>`;const response=await fetch('/api/admin/users',{headers:await apiHeaders()});const data=await response.json();if(!response.ok){content.innerHTML+=`<p class="empty">${esc(data.error||'No se pudieron cargar los usuarios.')}</p>`;return}const table=`<div class="card" style="margin-top:18px"><h2>Usuarios registrados</h2><div class="table"><table><thead><tr><th>Nombre</th><th>Correo</th><th>Rol</th><th>Acciones</th></tr></thead><tbody>${data.users.map(u=>`<tr><td>${esc(u.name||'Sin nombre')}</td><td>${esc(u.email)}</td><td><select id="role-${u.id}"><option value="RH" ${u.role==='RH'?'selected':''}>RH</option><option value="RESPONDENT" ${u.role==='RESPONDENT'?'selected':''}>Colaborador</option><option value="ADMIN" ${u.role==='ADMIN'?'selected':''}>Administrador</option></select></td><td><button class="row-button" onclick="changeUserRole('${u.id}')">Guardar rol</button> <button class="row-button" onclick="resetUserPassword('${u.id}')">Resetear contraseña</button> <button class="row-button delete" onclick="deleteUser('${u.id}')">Eliminar</button></td></tr>`).join('')}</tbody></table></div></div>`;content.innerHTML=content.innerHTML.replace(/<div class="card" style="margin-top:18px"><h2>Usuarios<\/h2>[\s\S]*?<\/div>/,table)}
async function changeUserRole(id){const role=document.querySelector(`#role-${id}`).value;const res=await fetch('/api/admin/users',{method:'PATCH',headers:await apiHeaders(),body:JSON.stringify({userId:id,role})});const data=await res.json();alert(res.ok?`Rol actualizado: ${roleName(role)}.`:(data.error||'No se pudo actualizar el rol.'));if(res.ok)adminUsers()}
async function deleteUser(id){if(!confirm('¿Eliminar este usuario de forma permanente?'))return;const res=await fetch('/api/admin/users',{method:'DELETE',headers:await apiHeaders(),body:JSON.stringify({userId:id})});const data=await res.json();alert(res.ok?'Usuario eliminado correctamente.':(data.error||'No se pudo eliminar el usuario.'));if(res.ok)adminUsers()}
